### ISSUE TITLE
[Bug] Crash on startup

### ISSUE THREAD

**Issue by Elnhomantia** [copycats-plus/copycats#100]
**Describe the bug**
A crash on start

**To Reproduce**
1. Launch the game
2. Crash

**Expected behavior**
A startup crash

**Screenshots**
![image](https://github.com/user-attachments/assets/338a2303-65c1-404b-9958-2a0f4fc75f58)

**Desktop :**
 - Minecraft Version: 1.20.1
 - Mod Loader : Forge
 - Mod Version : 2.0.0

**Additional context**
it work if I downgrade (with version 1.3.8)
Here is some logs
[latest.log](https://github.com/user-attachments/files/16286051/latest.log)

[crash-2024-07-18_18.03.52-fml.txt](https://github.com/user-attachments/files/16286053/crash-2024-07-18_18.03.52-fml.txt)

**Comment by Bennyboy1695** [comment]
Known compat issue with factory must grow. Already been fixed. Should be out asap

**Comment by Elnhomantia** [comment]
okay thx ! It was just to alert you in case you did not know
