### ISSUE TITLE
[Bug] Dedicated Server Crash Immediately On Startup

### ISSUE THREAD

**Issue by Epig-is-a-llama** [copycats-plus/copycats#101]
**Describe the bug**
Server crashes immediately on load with newest version with the crash report pointing to this mod with the following exception message:
`java.lang.RuntimeException: Attempted to load class net/minecraft/client/resources/model/BakedModel for invalid dist DEDICATED_SERVER`

**To Reproduce**
- Load the latest version of the mod (`copycats-2.0.0+mc.1.20.1-forge`) on a dedicated server (which previously worked with `copycats-1.3.8+mc.1.20.1-forge`).

**Expected behavior**
Server loads without incident as it did prior to updating.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Minecraft Version - `1.20.1`
 - Mod Loader - `Forge`
 - Mod Version `2.0.0`

**Additional context**

Crash-report:
[message2.txt](https://github.com/user-attachments/files/16287464/message2.txt)

**Comment by forest-cat** [comment]
I think im having the same issue #102

**Comment by Epig-is-a-llama** [comment]
> I think im having the same issue #102

Yep, looks like the same issue

**Comment by Bennyboy1695** [comment]
We are aware of the issue. Having some time fixing it though as i'm struggling to track down exactly this client class is supposedly coming from as the error lies big time.

**Comment by forest-cat** [comment]
> We are aware of the issue. Having some time fixing it though as i'm struggling to track down exactly this client class is supposedly coming from as the error lies big time.

Alright. Take your time. Thx for your work ^^

**Comment by johalun** [comment]
I had the same issue with 2.0.0 but 2.0.2 works.

**Comment by hlysine** [comment]
This has been fixed in v2.0.2+
