### ISSUE TITLE
[Bug] Copycat crashes after update

### ISSUE THREAD

**Issue by rymusov** [copycats-plus/copycats#104]
**Describe the bug**
After updating copycat - modpack crashes because design n decor
[crash-2024-07-18_22.34.19-fml.txt](https://github.com/user-attachments/files/16288345/crash-2024-07-18_22.34.19-fml.txt)
[latest.log](https://github.com/user-attachments/files/16288347/latest.log)

**To Reproduce**
1. Update copycat
2. Have latest design n decor
3. start
4. *boom*

**Expected behavior**
After updating copycat - modpack crashes because design n decor

**Desktop (please complete the following information):**
 - Minecraft Version: [e.g. 1.20.1]
 - Mod Loader FORGE
 - Mod Version 2.0.0

**Comment by hlysine** [comment]
This is an incompatibility with Create: TFMG and is not related to Design n Decor. It has been fixed since 2.0.1
