### ISSUE TITLE
[Bug] Create Copycats and Create Extended Cogwheels chunk corrupting incompatibility 

### ISSUE THREAD

**Issue by Penty2** [copycats-plus/copycats#105]
Game crashes with chunk getting corrupted if you try to apply any block to any of those copycat+ blocks: copycat shaft, copycat cogwheel, copycat large cogwheel.

0: add [Extended Cogwheels mod](https://modrinth.com/mod/extended-cogwheels/version/2.1.1-1.20.1-0.5.1.f-fabric) (this is version I have tested with)
1. Create world.
2. Place any of the following: copycat shaft, copycat cogwheel, copycat large cogwheel.
3. Click with any block that can alter copycats on this block.
4. Game crashes and if you try to load into this world again it will crash again.

 - Minecraft Version: 1.20.1
 - Mod Loader: Fabric
 - Mod Version: 2.0.2

https://mclo.gs/zQnwd1f

**Comment by hlysine** [comment]
This is now fixed in v2.0.3
