### ISSUE TITLE
[Bug] Crash when trying to open FramedBlocks tab

### ISSUE THREAD

**Issue by rbasamoyai** [copycats-plus/copycats#106]
**Describe the bug**
When running Copycats+ v2.0.2 on 1.18.2, trying to open the FramedBlocks mod tab results in a crash.
From the linked crash report, it appears that Copycats+ is trying to add its content to the tab. FramedBlocks's creative tab has validation code ([see here](https://github.com/XFactHD/FramedBlocks/blob/1.18.x/src/main/java/xfacthd/framedblocks/common/util/FramedCreativeTab.java)) that crashes the game.

This crash did not occur in the previous version of Copycats+ that I used, v1.2.5.

**To Reproduce**
1. Install Copycats+ v2.0.2 and the latest version of FramedBlocks (v5.11.5), as well as any required dependencies
2. Open the game and go into the creative mode tab
3. Click on FramedBlocks' tab
4. Game crashes, see error file for example

**Expected behavior**
The game should not crash.

**Screenshots**
N/A

**Desktop:**
 - Minecraft Version: 1.18.2
 - Mod Loader: Forge
 - Mod Version: 2.0.2

**Additional context**
Found in development environment while working on compatibility for Create Big Cannons
Crash report: [crash-2024-07-18_23.29.25-client.txt](https://github.com/user-attachments/files/16301691/crash-2024-07-18_23.29.25-client.txt)

Addendum: It also appears that Copycats+ adds the Copycat Box and Copycat Catwalk items to all tabs aside from those of Create (both function and decorative) and Create Big Cannons (likely due to how we register our creative tabs.)
![image](https://github.com/user-attachments/assets/edcc750b-746b-4dbd-9a02-7fa719d1a589)

**Comment by hlysine** [comment]
Ah my bad. I suspected that this would happen when I was fixing creative tabs for 1.18 but promptly forgot to test it out.

**Comment by hlysine** [comment]
Fixed in 2.0.3
