### ISSUE TITLE
[Bug] Copycat Cogwheels have no texture

### ISSUE THREAD

**Issue by mxnmnm** [copycats-plus/copycats#107]
**Is your feature request related to a problem? Please describe.**
When you jump on a copycat cogwheel (any size) the particles have no texture. 
![2024-07-19_01 54 23](https://github.com/user-attachments/assets/c3169f72-e197-41a0-9da6-1362ef85ec18)

**Describe the solution you'd like**
Ideally they should take the texture of whatever texture they are given.

**Comment by hlysine** [comment]
Can't reproduce in 1.20.1 Forge/Fabric. What version of the game are you using? Any other mods related to cogwheels installed?
![image](https://github.com/user-attachments/assets/105ae629-9c14-4201-af69-05b7466f3aa4)

**Comment by mxnmnm** [comment]
Fixed
