### ISSUE TITLE
[Bug] Crash after Schematic Canon try place copycat (slopes vertical and horizontal, empty or filled)

### ISSUE THREAD

**Issue by Dek03** [copycats-plus/copycats#108]
**Describe the bug**
When Schematic Canon from mod Create trying to place copycat it crashes the game. After that, after restarting game, block is placed where it should be.
(The game crashed whilst rendering block entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.BlockGetter.m_7702_(net.minecraft.core.BlockPos)" because "reader" is null)
[crash-2024-07-20_03.15.54-client.txt](https://github.com/user-attachments/files/16317462/crash-2024-07-20_03.15.54-client.txt)

**To Reproduce**
1. Make schematic of copycat block (4 different copycat block for sure (slopes for double sure)).
2. Try to build it with schematic canon.
3. Crash
5. Restart game and reenter world where block is placed.

**Expected behavior**
Place copycat blocks with canon without crashes.

**Desktop:**
 - Minecraft Version: 1.20.1
 - Mod Loader Forge
 - Mod Version 2.0.2

**Additional context**
Seems that problem with rendering launching animation from canon.

**Comment by hlysine** [comment]
This is fixed in v2.0.3
