### ISSUE TITLE
[Bug] Crash while launching on modrinth after update minutes ago

### ISSUE THREAD

**Issue by PaterFrog** [copycats-plus/copycats#109]
Here's the crash report from Modrinth, and latest.txt:
[crashrep](https://mclo.gs/aDz9LKXi)
[latest](https://mclo.gs/CcWg7Aa)
Note that it mentions BetterNether, too, but the crash only started happening after I updated your mod just now.

I just downgraded to the previous version (2.0.2) and the crash is fixed. Here's the live log of that:
[Live Log](https://mclo.gs/noZ88qY)

**Comment by PaterFrog** [comment]
And if it's of interest, here's my current list of mods:
[list](https://mclo.gs/2R0mrBf)

**Comment by hlysine** [comment]
The crash report is inaccessible and the client log shows no fatal errors.

**Comment by hlysine** [comment]
Please update to 2.0.4 and try again.

**Comment by PaterFrog** [comment]
The crash is unfortunately not fixed.
I have no idea why the link's broken, but here's a [new one](https://mclo.gs/y92qtqI).

Edit: nvm, Modrinth didn't actually update properly when I hit the update button, it went to 2.0.3, instead of *.4
2.0.4 seems to be fine.
