### ISSUE TITLE
Resource Loading Error (Non-Breaking)

### ISSUE THREAD

**Issue by ChloeDawn** [copycats-plus/copycats#11]
When loading resources, Minecraft prints the following error:
```
 [Worker-Main-34/ERROR] [minecraft/Util]: Invalid path in pack: copycats:models/block/copycat_base/README.md, ignoring
 ```
 This can be resolved by either excluding the file from published artifacts, or by using the [`filter`](https://minecraft.wiki/w/Resource_pack#Contents) section in `pack.mcmeta`.

**Comment by hlysine** [comment]
I see, thanks for the tip.
