### ISSUE TITLE
[Bug] Crash when loading into existing world

### ISSUE THREAD

**Issue by Xahria07** [copycats-plus/copycats#110]
**Describe the bug**
The game crashes when trying to load into an existing world. 

**To Reproduce**
I'm unable to replicate this behaviour outside of my existing world save. Creating a new world and placing down copycat blocks seems to be fine.

**Expected behavior**
For the game to load into the world without crashing

**Desktop (please complete the following information):**
 - Minecraft Version: 1.20.1
 - Mod Loader: Forge 47.2.30
 - Mod Version : 2.0.4

**Additional context**
Works fine when creating new worlds from scratch however.  The game loads in fine with version 1.3.8 of the mod but anything past version 2.0 seems to cause it. I've tried all versions up till 2.0.4.

I think its client sided as well since my dedicated server could start up just fine and the client crashes once it starts loading terrain. I have Embeddium and Embedidium++ installed and I believe it might be some rendering issue with a select few copycat block types that are causing this crash.

I figured its probably something to do with having rendering of some of the copycat blocks as when I rolled back to v1.3.8 a lot copycat blocks that already existed before reverted to its default texture and needed to completely replaced in order to have it mimic the desired block again.

I hope I've been detailed enough and if this is purely an issue with Embeddium I'll repost this over on their issues page. Thank you for your time!

Here is the crashlog.
[crash-2024-07-20_19.24.56-client.txt](https://github.com/user-attachments/files/16319984/crash-2024-07-20_19.24.56-client.txt)

**Comment by hlysine** [comment]
Thanks for the detailed report. This is a bug in our new copycat block model which makes it incompatible with certain complex blocks added by other mods. 

I'll post a build with the fix here once it's built, so you can verify that it works

**Comment by hlysine** [comment]
[UNZIP ME copycats-2.0.4-mc.1.20.1-forge-build.97.zip](https://github.com/user-attachments/files/16321047/UNZIP.ME.copycats-2.0.4-mc.1.20.1-forge-build.97.zip)

**Comment by Xahria07** [comment]
I can verify that this fix is working, loaded into my world save just fine and the previously affected copycat blocks that lost their textures are working as intended. 

Thank you so much for your quick response! I deeply appreciate this mod and the efforts of everyone working on it!
