### ISSUE TITLE
[Bug] Incorrect block face culling on copycat byte

### ISSUE THREAD

**Issue by Marco6789** [copycats-plus/copycats#112]
**Describe the bug**
Faces of the copycat byte are culled incorrectly.

**To Reproduce**
-Place down a copycat byte on a blocks right half
-place down a copycat byte diagonally across on a blocks left half
-place down a block on the left of the block that has the bytes
-you will see that the byte on the right has its left face culled incorrectly
-this works in any direction. the game treats all bytes on one half of the block as if they are obscured by bytes on the other half of the block even if there is only one byte in the other half of the block

**Expected behavior**
the bytes faces aren't culled when there is no other byte to obscure the face

**Screenshots**
How it looks:
![2024-07-21_10 41 57](https://github.com/user-attachments/assets/06e60d35-44cd-4bc8-8ad1-f88293801946)
How it is expected to look (when there is a block on the dirt)
![2024-07-21_10 42 06](https://github.com/user-attachments/assets/ff964bea-c9a5-46b1-babc-2ffd8bcbf44c)

**Desktop (please complete the following information):**
 - Minecraft version 1.19.2, Forge
 - Mod version 2.0.5 (also present on 2.0.4)

**Additional context**
not shown in screenshots, but behavior persists regardless of material used to fill the bytes. Doesn't happen with transparent blocks such as leaves or glass (presumably since culling is disabled for those blocks)

**Comment by hlysine** [comment]
Thanks for the report. Copycats have a custom culling algorithm that works fine in this case, but installing Sodium-like mods applies another round of culling which causes this issue. A small change has been made to disallow rendering mods from culling copycat faces.
