### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by AlcimosNetwork** [copycats-plus/copycats#114]
**Describe the bug**
Can't place Mechanical Belts on a copycat shaft.

**To Reproduce**
1. Place 2 copycat shafts.
2. Fill the copycat with a block.
3. Try to place the mechanical belt.

**Expected behavior**
I expect when you try to place a mechanical belt on the copycat shaft you will get a belt.
This should be the same like with normal create with the normal shafts.

**Information**
 - Minecraft version: 1.20.1
 - Forge
 - Mod version: 2.0.5

**Additional context**
Maybe the possiblity to also use it on a copycat shaft without the block inside the copycat shaft. But that would be optional.

**Comment by hlysine** [comment]
This isn't a bug because belts with shafts are separate blocks that we don't intend to add right now. We may reconsider this after copycat encased pipes/shafts.
