### ISSUE TITLE
Conflict with Diagonal Walls mod

### ISSUE THREAD

**Issue by KiyooChan-hub** [copycats-plus/copycats#118]
**Describe the bug**

**To Reproduce**
1. Install copycats and Diagonal Walls mod at the same time. (https://www.curseforge.com/minecraft/mc-mods/diagonal-walls)
2. Place a new copycats wall.

**Expected behavior**
1. Newly place a copycat wall, it turns into stone appearance and can't attach texture-block into it.
2. It only happens on newly-placed wall. Walls already placed seems to be fine.

**Screenshots**
![image](https://github.com/user-attachments/assets/7238add9-0f45-4e8d-be55-4aeff5388ef1)

**Desktop (please complete the following information):**
 - Minecraft Version: 1.20.1
 - Mod Loader: NeoForge 47.1.106
 - Mod Version 2.0.5

**Comment by hlysine** [comment]
This is already fixed in code but the fix hasn't been released yet. You can also avoid this issue by adding copycat walls to the `diagonalwalls:non_diagonal_walls` tag using a datapack.

**Comment by KiyooChan-hub** [comment]
Okay fine, I'm expecting the next release, cheers :D
