### ISSUE TITLE
[Bug] Copycat byte missing sides

### ISSUE THREAD

**Issue by PaleAsphodel** [copycats-plus/copycats#119]
**Describe the bug**
If copycat bytes are placed next to a textured copycat step, some sides of the bytes don't render.

**To Reproduce**
1. Place copycat step in top quarter of a block
2. Place 3 or 4 copycat bytes in top quarter of adjacent block
3. Add material to copycat step
4. One of the sides of the bytes stops rendering (whether they have a material or not)
5.  Probably also applies to other configurations and maybe not limited to bytes? I stumbled across it while building

**Screenshots**
![2024-07-23_20 21 54](https://github.com/user-attachments/assets/89ecf59f-c44f-4272-8c4f-ef8522866fd8)

**Desktop (please complete the following information):**
 - Minecraft Version: 1.20.1
 - Mod Loader: Forge
 - Mod Version: copycats-2.0.5+mc.1.20.1-forge

**Comment by hlysine** [comment]
This is a known issue that has been fixed. Will be available in the next update.
