### ISSUE TITLE
[Bug] crash loading the world

### ISSUE THREAD

**Issue by Rodrigo816** [copycats-plus/copycats#121]
### Issue Report

**Description:**
When I try to load into my world, it crashes. The issue seems related to the new additions in Coppycats 2.0.5, such as wheels and shafts. Removing a cogwheel from my world or downgrading the mod fixes the issue.

**Mods Required:**
- Embeddium
- Embeddium Extras
- Radium

**Forge Version:** 1.20.1

**Crash Log:**
[Crash Log](https://gist.github.com/Rodrigo816/ad56b4b313d5a1b3ff1beb86fab3f23e)

**Steps to Reproduce:**
1. Have a cogwheel in the world.
2. Load the world with Coppycats 2.0.5 installed.

**Additional Information:**
The crash is not always 100% reproducible; sometimes I can enter, but most of the time I get this error. The crash appears to be connected to new features introduced in the latest version of the mod.

**Comment by hlysine** [comment]
I can't reproduce this crash even with oculus and shaders installed. Judging from the crash report, this seems to be an incompatibility with mods that modify the rendering vertex format. Can you try removing mods from your pack to find out the minimal set of mods required to reproduce this crash?

**Comment by Rodrigo816** [comment]
> I can't reproduce this crash even with oculus and shaders installed. Judging from the crash report, this seems to be an incompatibility with mods that modify the rendering vertex format. Can you try removing mods from your pack to find out the minimal set of mods required to reproduce this crash?

Sorry, I suspect it's not related to your mod. Not sure what is causing it.
I can't make it crash now

**Comment by lemonhappy50-jpg** [comment]
wsup, maybe too late, but i find a solution, in your copycats jar, find a copycats-common.mixins.json, and delete "compat.rubidium.BlockOcclusionCacheMixin",
"compat.rubidium.BlockRendererMixin". The mod’s mixins were conflicting with Rubidium’s rendering system. Once we disabled the Rubidium-related mixins in the copycats-common.mixins.json
