### ISSUE TITLE
[Bug] Most stonecutting recipes seem to use incorrect tag (c:zinc_ingots instead of c:ingots/zinc)

### ISSUE THREAD

**Issue by Mirka1405** [copycats-plus/copycats#129]
**Describe the bug**
Most stonecutting recipes (for example, copycat door) use tag "c:zinc_ingots" instead of "c:ingots/zinc", which makes them uncraftable

**To Reproduce**
1. Use REI or other mods of this kind to see the item recipes
2. Look at recipes of items like copycat door, copycat slope etc.
3. Due to the wrong tag, the input is empty

**Expected behavior**
The items should use "c:ingots/zinc" in their recipe

**Screenshots**
The tags on the zinc ingot do not include "c:zinc_ingots"

![Image showcasing the tags of the zinc ingot](https://github.com/user-attachments/assets/1269a3f9-963c-4359-95ff-dea78d4663cb)

![Image showing the empty input slot](https://github.com/user-attachments/assets/2d6ee973-1cdd-49e3-860d-97d60e11f020)

**Desktop (please complete the following information):**
 - Minecraft Version: 1.18.2
 - Mod Loader: Fabric
 - Mod Version: 2.0.5

**Comment by Bennyboy1695** [comment]
I have just fixed it in the latest push. It should be released soon:tm: It likely got changed to be the incorrect tag when we had our big refactor and got ported backwards.
Until then if you have kubejs you should be able to very easily fix the recipes by adding the tag we currently use to zinc with that
