### ISSUE TITLE
[Suggestion] Copycat Doors!

### ISSUE THREAD

**Issue by Specimen-420** [copycats-plus/copycats#13]
Ill keep it short but Copycat doors would be pretty cool if possible! Understandable if not. Thanks!

**Comment by Daniel99j2** [comment]
Like the idea, no sure how it would look (what door model to use?)

**Comment by SickElmo-GH** [comment]
I was thinking about something simple like Framedblocks do. So just a plane with no window or anything and you slap top and bottom texture on it.

**Comment by satoon10** [comment]
Added in 2.0.0
