### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by PaleAsphodel** [copycats-plus/copycats#131]
Describe the bug
When using blocks that have both "vertical" and "horizontal" connected textures as material for copycat blocks, some of the connected textures don't seem to work.

To Reproduce

 1. Place any kind of adjacent copycat blocks
 2. Use a material block that has connected textures both ways, for example Create: Andesite Pillar
 3. When rotating the material so that the column "sides" connect the way a column would normally connect vertically (see screenshot 1), it works just fine
 4. However, when rotating the material again so that the sides and top of the column should combine horizontally, connected textures fail (see screenshot 2: to the left, the failed experiment, and to the right, the way the textures normally connect when the blocks are arranged that way)
 5. The same configurations were tested for the 2 native Create copycats (Copycat Step and Copycat Panel): the problem does not occur and the textures connect seamlessly for every possible orientation

Screenshots
![2024-07-31_20 18 39](https://github.com/user-attachments/assets/7a62ec50-84f7-455f-a09a-ddf06a30542b)
![2024-07-31_20 21 24](https://github.com/user-attachments/assets/6a0a8a68-e271-4fa4-b52f-976b178e3165)

Desktop (please complete the following information):

    Minecraft Version: 1.20.1
    Mod Loader: Forge
    Mod Version: copycats-2.0.5+mc.1.20.1-forge

**Comment by hlysine** [comment]
I was confused by a patch in the pillar CT logic that made things worse and decided to remove it. Turns out this is what the patch was trying to fix (but without success). I've now replaced it with a new patch and confirmed that it works.
