### ISSUE TITLE
[Bug] Copycat walls appearing as stone block

### ISSUE THREAD

**Issue by queefmasterlion** [copycats-plus/copycats#132]
**Describe the bug**
When placing a copycat wall, it appears as a stone block

**To Reproduce**
1. Place a copycat wall

**Screenshots**
![image](https://github.com/user-attachments/assets/558cee0c-0a4c-434c-a4ce-b3eba48116a1)
![image](https://github.com/user-attachments/assets/0a0f9025-112c-4b3c-b481-df2348f27a97)

**Desktop (please complete the following information):**
 - Minecraft Version: 1.20.1
 - Mod Loader Fabric
 - Mod Version 2.0.5

**Additional context**

**Comment by Bennyboy1695** [comment]
Thats because of an incompatibly with diagonal walls mod. We have disabled it in a future version but for now you should disable it in the config for diagonal walls
