### ISSUE TITLE
[Bug] Pressure plate can be destroyed by water

### ISSUE THREAD

**Issue by SterixCraft** [copycats-plus/copycats#134]
Just as the title says, however this does not happen to the vanilla ones.
![515c19ce-27f0-40a6-9ac2-0ee859e4ae97](https://github.com/user-attachments/assets/65d65e07-95a2-4482-9899-75d4fc23ce47)

**Comment by hlysine** [comment]
I've made buttons waterproof as well for bonus QoL.
