### ISSUE TITLE
[Bug] Update from 2.0.5 1.20.1 to 2.1.0 1.20.1 causes some already placed copycats to be permanent

### ISSUE THREAD

**Issue by Barerock** [copycats-plus/copycats#135]
**Describe the bug**
Copycats that have already been placed before updating sometimes can't be replaced with the same type. Even if another block is placed first, then removed, then replaced with a copycat of the same type it will revert to the block texture it was beforehand.

**To Reproduce**
1. Install dependencies and place a copycat stair and add a block to it
2. Install the update
3. break and place a new copycat stair of the same type in the same orientation

**Expected behavior**
Well they should break and place normally.

**Screenshots**
![2024-08-01_18 44 03](https://github.com/user-attachments/assets/0c0e0d2d-bba5-4f71-9865-d0c70267e91a)
![2024-08-01_18 44 14](https://github.com/user-attachments/assets/a135c487-2f9c-4823-8cfe-82179a76cea6)
![2024-08-01_18 44 24](https://github.com/user-attachments/assets/10c08b7b-aaae-4887-904f-69d10a2de6a7)

1. a copycat vertical stair with layered granite bricks texture
2. broken
3. placed back, it immediately converts to the previous texture, only being a copycat texture for a split second

**Desktop (please complete the following information):**
 - Minecraft Version: [1.20.1]
 - Mod Loader[Forge 47.2.20]
 - Mod Version [2.1.0]

**Additional context**
This specific area isn't the _worst_ place for this to happen, because brick stairs exist, but other places in this structure do require texturing and now I can't texture them properly or at all.

**Comment by Barerock** [comment]
Placing a DIFFERENT kind of copycat, for instance a half slab, will update the block data and allow normal behavior again. This does NOT occur with panels, at the very least, which is the only other block immediately tested in this tunnel.

**Comment by Barerock** [comment]
Placing another stair and texturing it will make the block data bug out again, actually. I think this is just a bug with the 2.1.0 version, not with updating.

**Comment by hlysine** [comment]
I think I know why this is happening. Before we push an update, you can wrench the copycat before breaking it to change the texture.

**Comment by Barerock** [comment]
Awesome, thanks for being on top of it. <3
