### ISSUE TITLE
copycat slab bug 

### ISSUE THREAD

**Issue by Mrtrainman** [copycats-plus/copycats#137]
**Describe the bug**
assemble a train with a texture copycat is fine but disassembling it with lost texture but on the double slabs one it would flip from a different direction when disassemble a train

**To Reproduce**
1. building a train with copycat slab
2. assemble the train its fine
3. disassemble the train
4. it will lose texture or flip a different direction

**Expected behavior**
none

**Screenshots**
none

**Desktop (please complete the following information):**
 - Minecraft Version: [e.g. 1.20.1]
 - Mod Loader[e.g. Forge]
 - Mod Version [e.g. 2.1.1]

**Additional context**
none

**Comment by hlysine** [comment]
It's just been fixed not long ago. An update will be released soon for this.
