### ISSUE TITLE
Copycat panels with connecting translucent textures are not seamless

### ISSUE THREAD

**Issue by DadamaldaDad** [copycats-plus/copycats#140]
**Describe the bug**
When you place translucent blocks with connecting textures in copycat panels, the transition is not seamless and shows a weird strip.

**To Reproduce**
1. Place 2 copycat panels next to each other
2. Place something like framed glass in the copycats
3. Enjoy not being able to unsee it

**Expected behavior**
The copycat panels should have proper connecting textures without a weird strip in-between.

**Screenshots**
![Snímek obrazovky 2024-08-04 161316](https://github.com/user-attachments/assets/9ad9e116-41a1-491f-9831-a3aad91f9156)
Framed glass and copper windows from Create Deco

**Desktop (please complete the following information):**
 - Minecraft Version: 1.20.1
 - Mod Loader: Forge
 - Mod Version: 2.1.1

**Additional context**
Unnecessary

**Comment by Bennyboy1695** [comment]
Similar issue to #128. Not something we can really do anything about sadly
