### ISSUE TITLE
[Bug] Copycats not emitting light

### ISSUE THREAD

**Issue by NeatoNeato** [copycats-plus/copycats#142]
**Describe the bug**

Copycats emit light properly when copying light emissive blocks in version 2.05, but stop emitting light when upgrading to versions 2.10 and above. 
Further, new copycats placed under v 2.10 and above do not emit light.

**To Reproduce**

Using modded minecraft loaded with copycats-plus versions 2.10, 2.11, or 2.12:

1. place copycat
2. click on copycat with light emissive block
3. observe error:  copycat does not emit light

**Expected behavior**

Copycat should emit light.

**Screenshots**

First screenshot, using version 2.05: copycats emit light
![2024-08-06_22 47 05](https://github.com/user-attachments/assets/c42bc959-3ba5-4e60-a89e-edf4fe51d23a)

Second screenshot, using version 2.10: copycats do not emit light
![2024-08-06_22 51 38](https://github.com/user-attachments/assets/9a67a16e-aafa-45f7-8e91-38acffb938d5)

**Desktop (please complete the following information):**

 - Minecraft Version: 1.19.2
 - Mod Loader: Forge
 - Mod Version: 2.10, 2.11, 2.12

**Additional context**

Again, copycats emit light properly using version 2.05

**Comment by hlysine** [comment]
Please make sure that you don't have Starlight installed. Light emission before v2.1 was client-side only and was usually lost after you restart your game. Since v2.1, we have an experimental fix for the issue but it isn't compatible with Starlight.

**Comment by NeatoNeato** [comment]
Thanks for the idea. I don't have Starlight and have never used it.

Are there other mods that cause the same effect?  

The strange thing is that I have the opposite problem of most users--light emission worked fine in 2.05 for me, and stopped working in 2.10 with the fix.  Staying on 2.05 is a reasonable solution; I was just hoping to make use of the new fixes and features of 2.10+.

**Comment by hlysine** [comment]
We have implemented a more proper fix in Copycats+ v2.1.3 which should hopefully solve all lighting issues for now. However, this issue is more deep-rooted and will require an update from mod loaders to completely fix.
