### ISSUE TITLE
[Bug] Game crashes when copycat fence gate is placed.

### ISSUE THREAD

**Issue by Red004F** [copycats-plus/copycats#144]
Game crashes when a copycat fence gate is placed.

**Steps to reproduce the behavior:**
1. Obtain a copycat fence gate.
2. Place said fence gate.
3. Game should crash and give as exit message:
_The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot set property BooleanProperty{name=waterlogged, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{copycats:copycat_fence_gate}_
(Exit code: -1)

**Expected behavior:**
The game should not crash.

**Desktop:**
Minecraft Version: 1.20.1
Mod Loader: Forge - 47.3.5
Mod Version: 2.1.2

**Comment by Bennyboy1695** [comment]
we need the crash report please

**Comment by Red004F** [comment]
Here
[crash-2024-08-09_23.32.11-client.txt](https://github.com/user-attachments/files/16567056/crash-2024-08-09_23.32.11-client.txt)

**Comment by Bennyboy1695** [comment]
Ahh appears to be an issue with the migration manager from Create: Connected @hlysine. There should be an option in connected's config to turn off the migration, that should fix it until theres a fix for it in Create: Connected

**Comment by hlysine** [comment]
Yeah please turn off copycat migration in Create: Connected for now. I've already fixed this issue but there's a lot of work ongoing in C:Connected so I'm not releasing an update yet.

**Comment by hlysine** [comment]
This has been fixed in Create: Connected 0.9.0 or above.
