### ISSUE TITLE
[Bug] Game crashes when trying to blend with ME cable facades.

### ISSUE THREAD

**Issue by MEEPofFaith** [copycats-plus/copycats#145]
**Describe the bug**

Connected textures between the top of a copycat stair and a ME cable facade kills the game.

**To Reproduce**
1. Place a copycat stair against a cable with a facade on top with a connecting texture, such as andesite casing.
2. Attempt to put the same block in the copycat stair.
3. Game Crashes.

**Expected behavior**

The game not to crash.

**Screenshots**

![2024-08-09_15 57 22](https://github.com/user-attachments/assets/ac973e16-57b2-4c54-90f4-0ab99acbc947)
![2024-08-09_16 04 31](https://github.com/user-attachments/assets/3d5db654-8628-4ff6-8ac8-2941f0db77a2)
(Game crashes after putting in the casing).

**Desktop (please complete the following information):**
 - Minecraft Version: 1.20.1
 - Mod Loader Fabric
 - Mod Version 1.3.8

**Additional context**

Copycat stair:
[crash-2024-08-09_15.41.16-client.txt](https://github.com/user-attachments/files/16567518/crash-2024-08-09_15.41.16-client.txt)

Copycat vertical stair:
[crash-2024-08-09_16.04.38-client.txt](https://github.com/user-attachments/files/16567583/crash-2024-08-09_16.04.38-client.txt)

**Comment by hlysine** [comment]
Please try again with Copycats+ 2.1.2. There has been massive changes in the rendering system since 1.3.8 so I'm not sure if this issue exists anymore.

**Comment by MEEPofFaith** [comment]
No issues in 2.1.2
