### ISSUE TITLE
[Bug] Schematicannon tries to place air when trying to place multistate copycat blocks

### ISSUE THREAD

**Issue by Tera458** [copycats-plus/copycats#147]
**Describe the bug**
When making a schematic containing copycat blocks allowing multistate and putting it in a schematicannon, a majority of those copycat blocks will cause the schematicannon to say it requires air. I only managed to pinpoint it to bytes and half layers, wether they are full with the same materials, made out of different materials, same material of different orientations, or not full, as well as double slabs made out the same materials, made out of different materials but one has a different orientation, or same materials but different orientations.

**To Reproduce**
1. Place copycat blocks which allow multistates
2. Create a schematic with them inside
3. Place the schematic in a schematicannon and provide the needed materials, make sure skip missing blocks isnt selected
4. Schematicannon will be stuck trying to place air
5. If missing blocks are skipped, most multistates copycat blocks will not have been placed

**Expected behavior**
The schematicannon shouldnt interpret those blocks as air.

**Screenshots**
![Screenshot_2667](https://github.com/user-attachments/assets/d9c487c5-8eba-4d1c-8a2b-665ed3348faa)
![2024-08-17_15 43 34](https://github.com/user-attachments/assets/d8991686-96ea-4141-bc1c-35533b8dd5ae)

**Desktop (please complete the following information):**
 - 1.20.1
 - Fabric
 - 2.1.2 (Create Fabric 0.5.1)

**Additional context**
My only guess of the cause would be some kind of character limit for the blockstates.
Creative mode direct placement works flawlessly, and material checklists list the materials accurately

**Comment by hlysine** [comment]
I haven't investigated it in detail but my guess is that the `getRequiredItems` method is buggy and lists air as a requirement for unfilled parts of a multi-state.

**Comment by SageofTurtles** [comment]
Our server is currently experiencing this issue as well (same Minecraft/Fabric mod versions).

**Comment by hlysine** [comment]
This has been fixed in e1035289b719998ff0e833c03357d1ce2ac4e51c
