### ISSUE TITLE
[Bug] Softlock with Carry On

### ISSUE THREAD

**Issue by AlohaXChicken** [copycats-plus/copycats#148]
When picking up a door using the Carry On mod, you are unable to put it down without dying (And if you have a gravestone mod it will end up back in your inventory)

**To Reproduce**
Download Carry On and Copycats+ ofc
Place down a copycat door
Shift RClick on the door to pick it up
It cannot be put down

**Expected behavior**
Either you shouldn’t be able to pick up the copycats cause that doesn’t make sense, or you should at least be able to put them down

 - Minecraft Version: 1.18.2
 - Mod Loader: Forge
 - Mod Version:
    Copycats+ 2.1.2
    Carry On 1.18.2-1.17.2.15

**Additional context**
It might be cause the door is 2 blocks while everything else is one

**Comment by hlysine** [comment]
I don't think Carry On works with regular doors, right? Picking up regular copycats still sort of makes sense, but a door feels too big to be carried. We should probably just prevent doors from being picked up.

**Comment by hlysine** [comment]
Actually, having read the source code of Carry On, it's probably better that you bring the issue to the dev of Carry On instead. They already have a long list of incompatible modded blocks, so it should be easier for them to add one more than for us to patch their logic.
