### ISSUE TITLE
[Bug] Block Dupe with VS2

### ISSUE THREAD

**Issue by souldbminerr** [copycats-plus/copycats#151]
**Describe the bug**
You can duplicate blocks with VS2

**To Reproduce**
Assemble a ship with a filled copycat, block in copycat will be dropped, while copycat will still be fillled on ship

**Expected behavior**
The block should not be dropped

Fabric 1.20.1 2.1.2

**Comment by hlysine** [comment]
This is a bug in VS2: https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/698
