### ISSUE TITLE
[Bug] Exception when loading copycats:copycat_byte texture, using material colour.

### ISSUE THREAD

**Issue by dilleron3425** [copycats-plus/copycats#152]
**Describe the bug**
When loading chunks where the Copycats mod is used - Minecraft crashes.

**Desktop**
 - Minecraft Version: 1.20.1
 - Mod Loader: Forge 1.20.1-47.3.0
 - Mod Version: 2.1.2+mc.1.20.1-forge

**Comment by hlysine** [comment]
Please post your crash report.

**Comment by dilleron3425** [comment]
Published a post

**Comment by hlysine** [comment]
I don't see any fatal errors in the log, which means the game probably hasn't crashed. The line you are pointing towards has a severity of "info", which means it's a handled exception and is not the source of whatever issue you are having.
