### ISSUE TITLE
[Bug] Copycat Door and Iron Door textures misaligned

### ISSUE THREAD

**Issue by capyisslay** [copycats-plus/copycats#153]
When giving Copycat Door/Iron Door a texture of a block, the texture will be misaligned in the center (see screenshots)
On the left and in the middle are doors and on the right are blocks

**How to reproduce**
1. Download Copycats+ (duh)
2. Place a Copycat Door and Copycat Iron Door

Minecraft Version: 1.20.1
Mod Loader: Forge
Mod Version: 2.1.2
 
![1](https://github.com/user-attachments/assets/f18cc16a-a0fa-4b07-b26c-e39fe51d0218)
![2](https://github.com/user-attachments/assets/22a125cf-feec-4d90-88d9-7583093b9680)

**Comment by Bennyboy1695** [comment]
This is kinda on purpose. We slice the texture up and re-use parts of it to make the texture look better on most blocks. Some like this end up looking not as good though

**Comment by capyisslay** [comment]
oh ok. would be nice if you could disable it in the settings
