### ISSUE TITLE
[Bug] Schematicannon can't handle copycat layer items properly

### ISSUE THREAD

**Issue by joernott** [copycats-plus/copycats#155]
**Describe the bug**
Copycat layers are a bit special, as a block can contain between 1 and 8 layers, requiring 1-8 layer items. Even if you have enough layer items in the adjacent inventory, if the number of layer items needed is more than the number of items in the stack, the cannon stops and complains about missing items.

**To Reproduce**
1. Place 6 copycat layers in a block
2. Record this as a new blueprint
3. Place the blueprint and put it into the cannon.
4. Put 5 layers in the first slot of a chest next to the schematicannon and an additional layer into the 2nd slot.
5. Start printing

**Expected behavior**
The schematicannon takes the additional required layers from the next inventory slot.

**Desktop (please complete the following information):**
 - Minecraft Version: 1.20.1
 - Mod Loader Fabric
 - Mod Version 2.1.2

**Additional context**
I opened this bug [in the create project issue tracker](https://github.com/Creators-of-Create/Create/issues/6857) and it got closed with the recommended solution

> Whatever mod adds copycat layers should also implement ISpecialBlockItemRequirement to properly pass the required items

**Comment by Doppel-R101** [comment]
Can confirm this is also on Forge

**Comment by hlysine** [comment]
We do implement the ISpecialBlockItemRequirement interface properly. I suspect that this is a Create issue where the cannon doesn't know how to gather items for one requirement from two different storages.

**Comment by joernott** [comment]
That was my assumption as well, because the cannon can clearly handle picking up a copycat block and the block it uses for it's appeareance. It can also pick up all the layers as long as the first slot of the inventory containing copycat  layers contains >= the number of layers it needs. It only fails if the first inventory slot it looks at contains fewer layers and it would have to pick up the rest from a different slot. Sadly, they closed the issue quite quickly pointing me to you guys.
