### ISSUE TITLE
[Bug] All blocks uncraftable on Fabric due to crafting only using forge:ingots/zinc

### ISSUE THREAD

**Issue by mennockramer** [copycats-plus/copycats#16]
The equivalent Fabric tag to use is `c:zinc_ingots`.

**Comment by connieprice** [comment]
This is still a problem as the tag in the fabric recipes is defined as `c:ingots/zinc` instead of `c:zinc_ingots`

**Comment by Bennyboy1695** [comment]
this should be fixed in the newer versions of the mod
