### ISSUE TITLE
[Bug] Crash after updating the newest version

### ISSUE THREAD

**Issue by QianFuv** [copycats-plus/copycats#161]
CreateCopycats+ --- V2.1.2 -> V2.1.3
Crash disappears after rolling back the version.
https://mclo.gs/mArqYih

**Comment by Bennyboy1695** [comment]
Can we possibly get your latest.log for this crash please? If you've already downgraded the version again it will be one of the .gz files. So it might be easier to upgrade again to get the log

**Comment by QianFuv** [comment]
Latest log: https://mclo.gs/yjgwOWl
Crash report: https://mclo.gs/KvGWGTG
They belong to the same crash.

**Comment by hlysine** [comment]
Thanks for the report. This has been fixed in v2.1.4
