### ISSUE TITLE
Copycat board has physics collision when used on the ship in Valkyrien Skies

### ISSUE THREAD

**Issue by Rcc-xyz** [copycats-plus/copycats#167]
Copycat board has physics collision when used on the ship in Valkyrien Skies. 
Copycat board are often used in some narrow parts of machines, and physics collision affects the movement of the machine. 
I think Copycat boards without physics collision are a better choice.

**Comment by hlysine** [comment]
This issue has been brought up before. Whether copycats have collision on ships is controlled by VS2, not us, so you may want to ask them how they handle blocks with narrow hitboxes.

**Comment by Rcc-xyz** [comment]
OK, thanks for your answer.
