### ISSUE TITLE
[Bug] 1.20.1 Sodium 6.0-alpha.3

### ISSUE THREAD

**Issue by worm-in-concrete** [copycats-plus/copycats#169]
**Describe the bug**
 I place any block from Copycats+ and minecraft crashes.

**To Reproduce**
 Place any block from Copycats+.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Minecraft Version: [1.20.1]
 - Mod Loader[Fabric]
 - Mod Version [copycats-2.1.4 mc.1.20.1-fabric]

**Additional context**
 I know that officially Sodium 0.6.0 doesn't support Fabric 1.20.1, but I'm not sure if it's the Sodium mod that's the problem, because the 
 500+ mods in my modpack (https://mclo.gs/gOHrWlF) seem to work... I also tried running only Copycats+, Create and Sodium 
 (https://mclo.gs/4mv9Utj).

**Comment by Bennyboy1695** [comment]
The issue is that the class the copycats mod si looing for in sodium doesnt exist. Likely because its a major change version and has either moved or removed the class we depend on. Best bet would be to use a officially supported version of sodium for the version you are on

**Comment by worm-in-concrete** [comment]
If Sodium 6 starts officially supporting Fabric 1.20.1, will you update your mod?

**Comment by Bennyboy1695** [comment]
Yes if the version becomes an official version for 1.20.1 we will update to work with it. But until then it would be more effort for us to support the two versions especially because the 6.0 versions is currently alpha meaning it can still change

**Comment by worm-in-concrete** [comment]
thanks!
