### ISSUE TITLE
Slab always gets placed vertically

### ISSUE THREAD

**Issue by bauerwilhelm** [copycats-plus/copycats#17]
There seems to be a problem with the slab. I have to place it like 4 times each time to get placed horizontally. It's super practical to have the ability to place it vertical, but for now it is "too willing" to be vertical. It's even more complicated imo when there's nothing under the slab, so it's the upper half of a halb slab block. Do you know what I mean?😅

**Comment by hlysine** [comment]
It's because the slabs follow the direction you are looking in, so you need to look down a bit more to place the slab horizontally.
