### ISSUE TITLE
[Bug] Lagspike due to com.copycatsplus.copycats.compat.Mods.rl()

### ISSUE THREAD

**Issue by Bomb787** [copycats-plus/copycats#173]
I've been getting some weird FPS drops while playing my personal pack, and Spark seems to say it's coming from Copycats+. Did a little bit of testing and it seems like it's correct.

**To Reproduce**
1. Install Copycats+
2. Open a world
3. Load some chunks (more apparent if moving quickly, speed 255 on a superflat world).
4. FPS drops much more than without Copycats+ installed.

**Expected behavior**
The game should not be losing that much FPS.

**Screenshots**
![Screenshot 2024-11-03 015127](https://github.com/user-attachments/assets/dca622c0-3201-4dd6-897b-a1b9d3f68f8f)

**Desktop:**
 - Minecraft Version: 1.20.1
 - Mod Loader: Forge 47.3.11
 - Mod Version: 2.1.4

**Additional context**
Strangely, the issue is even more pronounced if WorldEdit is installed.

**Comment by hlysine** [comment]
Thanks a lot for the profiling. This should be an easy fix by caching the resource location.
