### ISSUE TITLE
[Bug] Lag spikes because of dynamic lights

### ISSUE THREAD

**Issue by KostromDan** [copycats-plus/copycats#176]
**Describe the bug**
Moving dynamic lights source with enabled ModernFix `mixin.perf.deduplicate_location=true` causing lag spikes
![image](https://github.com/user-attachments/assets/83d28e87-dd4c-4965-960e-f7c8a86ca071)
This happens because CopyCats constructs `new ResourceLocation`  very many times per tick at `com.copycatsplus.copycats.compat.Mods.rl()`, which shouldn't happen.
https://spark.lucko.me/FYo6L9kJjY
![image](https://github.com/user-attachments/assets/fdc87e7a-5bf4-4d06-84a2-1d7add342f24)

**To Reproduce**
1. Modlist:
![image](https://github.com/user-attachments/assets/a31a2ff3-a330-469a-8323-ee2066b7103a)
2. Add newline to `modernfix-mixins.properties`
```properties
mixin.perf.deduplicate_location=true
```
3. Modify in `betterf3.toml`:
```toml
[general]
	always_show_tps = true
```
to see profiler graphics.
4. Take torch in hand and run. See lag spikes.

**Desktop (please complete the following information):**
 - Minecraft Version: 1.19.2
 - Mod Loader: Forge
 - Mod Version: 2.1.4

**Comment by KostromDan** [comment]
I suggest to cache `ResourceLocation`. If it's new, call `new ResourceLocation` and add result to cache.
If it's in cache return from cache.

**Comment by Bennyboy1695** [comment]
We have already cached the resource location in a test build. It should be out soon:tm: if theres nothing wrong with it
