### ISSUE TITLE
[Bug] Slabs are only placed vertically when Vertical Slab is installed

### ISSUE THREAD

**Issue by davfrance** [copycats-plus/copycats#178]
**Describe the bug**
Slab can only be placed vertically, shifting, clicking on other blocks and or trying to rotate them with wrench don't do anything

**To Reproduce**
1. Download [Vertical Slab Compact](https://www.curseforge.com/minecraft/mc-mods/vertical-slabs-compat)
2. Try to place a slab

**Expected behavior**
Slab should be horizontal and should be vertical only when crouching 

**Screenshots**
![2024-12-14_12 11 06](https://github.com/user-attachments/assets/b416dfbe-19e7-4ea5-b03e-3d68640b8404)
(horizontal slabs are framed blocks)

**Desktop (please complete the following information):**
 - Minecraft Version: [1.20.1]
 - Mod Loader: Forge 47.3.0 Client, 47.3.12 Server
 - Mod Version: Vertical Slab 2.4, Copycats 2.1.14

**Additional context**
Quark is required for Vertical Slab, but I don't think that's the issue

**Comment by Bennyboy1695** [comment]
Copycat slabs can already be placed in all directions without the need of an extra mod. And the wrench won't rotate them because the wrench removes the applied texture.
But its likely the vertical slabs mod is setting too high of a priority or something and breaking our normal slab functionality
