### ISSUE TITLE
Mixins for base Create Copycats invalid on 1.18.2

### ISSUE THREAD

**Issue by Endalion** [copycats-plus/copycats#18]
In 1.18, base create copycats do not have `canConnectTexturesToward`, which causes a crash at 
https://github.com/copycats-plus/copycats/blob/c2b579dea3254bcba8e77e8e1d8d472077637c5e/src/main/java/com/copycatsplus/copycats/mixin/copycat/ConnectedTextureBehaviourMixin.java#L34
when using connected textures.

**Comment by Bennyboy1695** [comment]
Should be fixed in the newer versions of the mod
