### ISSUE TITLE
Modrinth Fabric version has wrong dependencies

### ISSUE THREAD

**Issue by dhouck** [copycats-plus/copycats#20]
The latest Fabric version on Modrinth, https://modrinth.com/mod/copycats/version/1.1.1-mc1.20.1-fabric, says it requires Create.  Which sounds right, except that points to the Forge version of Create.  The Fabric version of this mod should instead require https://modrinth.com/mod/create-fabric.

**Comment by Bennyboy1695** [comment]
Thanks for posting that. They should be fixed now

**Comment by dhouck** [comment]
Indeed it is, thanks!
