### ISSUE TITLE
Incompatibility with Create Fabric 0.5.1f

### ISSUE THREAD

**Issue by JensenJ** [copycats-plus/copycats#22]
I updated Create as the new patch (0.5.1f) on Fabric released today. Game will not launch with this addon installed. It seems create changed their creative mode tab implementation and any addon that adds items/blocks to the normal Create tab is broken. 

Log: 
[latest.log](https://github.com/copycats-plus/copycats/files/14547674/latest.log)

**Comment by Bennyboy1695** [comment]
large version changes like that are never likely to be compatible without an update from the addons. I recommend downgrading create again until the addons can get an update out.
Thanks for informing us though we will get an update out asap

**Comment by Sunconure11** [comment]
Can confirm the same issue with 1.19.2.

**Comment by PolyframeX** [comment]
Latest version still results in a crash on fabric 1.20.1

**Comment by pauliesnug** [comment]
This was fixed in 1.2.2 and 1.2.1
