### ISSUE TITLE
ConnectedTextureBehaviour FAILS with other Create addons

### ISSUE THREAD

**Issue by ImAK9** [copycats-plus/copycats#26]
### Versions:
Fabric API: 
**0.92.0**
Copycats: 
**1.2.0**
Create: 
**0.5.1f**

---

Crashlog: https://hastebin.skyra.pw/zoredahede.yaml

Full Log: https://hastebin.skyra.pw/iseguhubul.swift

**Comment by Bennyboy1695** [comment]
Should be fixed now. New versions are being reviewed on CF and Modrinth
