### ISSUE TITLE
Crashing on a server when placing a gearbox next to copycats+ block

### ISSUE THREAD

**Issue by CDNHeadls** [copycats-plus/copycats#29]
So to (hopefully) replicate this issue, place a gearbox next to copycats+ layer block placed in vertical position, this absolutely breaks the region around and whenever any player gets near it crashes nearly instantly. Im leaving a crash report (with the modlist) down here. I'd really hope for this bug to be fixed because it makes my pretty valuable world unplayable

[crash-2024-03-17_22.35.51-client.txt](https://github.com/copycats-plus/copycats/files/14629005/crash-2024-03-17_22.35.51-client.txt)

**Comment by Bennyboy1695** [comment]
This issue should be fixed in the latest version
