### ISSUE TITLE
game crashes when rendering chunk witch framed glass block.

### ISSUE THREAD

**Issue by Aaron112207** [copycats-plus/copycats#30]
game crashes when rendering chunk witch framed glass block. First I posted issue on creat but they say it's copycat+ issue.
Minecraft:1.18.2
Forge:40.2.17
Java:Adoptium-21.0.2.13
All mods and version in crash log:
https://gist.github.com/Aaron112207/dbc0edf9e47f6f7804263c838731cbda
It happened on friend lan world(i place framed glass block and we both get same crash report) I didn't try to do anything because we didn't have a lot of time since then.

**Comment by Aaron112207** [comment]
My issue is very close to issue #29 (only deference is block placed (I didn't read this crash log))glass was placed close to vertical slab but I don't remember if it was next to but crash appear instantly when block was placed block texture didn't even load.

**Comment by Bennyboy1695** [comment]
This issue should be fixed in the latest version
