### ISSUE TITLE
Bug: Lightning not working correctly

### ISSUE THREAD

**Issue by RedCrafter07** [copycats-plus/copycats#32]
Hi there!
First of all, I have to say I love this mod - it has a lot of very useful design functionality. Thank you!

I've recently found a bug while building my factory - If you use a texture, like of a redstone lamp, the lightning works once you place it, however if you re-open the world (only tested on single player), the lightning seems to be gone. I think it might be because of the way you load the new textures and recalculate the lightning? But I'm not sure.

Thanks for taking your time and reading this!

**Comment by RedCrafter07** [comment]
Update: I found out it's an issue with the Create Copycat implementation

**Comment by Bennyboy1695** [comment]
I was just about to say, we extend the base create copycat classes to make ours. So its likely an issue with create and not our mod

**Comment by RedCrafter07** [comment]
I'll look at the Create Mod's repo and file an issue there if someone else hasn't done that already - Thanks for your time anyways!

**Comment by RedCrafter07** [comment]
For anyone interested: Here's the issue in the Create Repo: https://github.com/Creators-of-Create/Create/issues/4889
