### ISSUE TITLE
Mod is incompatible with Addtional Placements

### ISSUE THREAD

**Issue by Enderteck** [copycats-plus/copycats#40]
[Addtional Placements](https://modrinth.com/mod/additional-placements) allows you to place slabs and stairs verticlly with a very nice block overlay. Unfortunatly this mod seems to override this feature on it's blocks. Addtional Placements usually works with modded slabs and stairs so it would be great if it could get fixed.

![Screenshot](https://github.com/copycats-plus/copycats/assets/123917079/bdbf754f-fa0b-4eff-b637-9c352464310c)

[Screen Recording.webm](https://github.com/copycats-plus/copycats/assets/123917079/4461c628-bc40-471f-8f55-a374e46685da)

**Comment by Bennyboy1695** [comment]
We specifically disabled functionality with that mod because it was causing crashes when used with our blocks. We may see if compatibility can be an option in the future, but as of right now it is forced disabled on blocks from our mod.
