### ISSUE TITLE
Copycat blocks containing light-emitting blocks lose their light values after a relog

### ISSUE THREAD

**Issue by goldrat1** [copycats-plus/copycats#43]
Any Copycat block that emits light from their block source (i.e if they have Glowstone in it), they properly produce light as expected, however leaving the world (singleplayer) and loading back into it causes the lighting to glitch out and light levels to drop again.
Examples below.
Before relog, using a Haunted Bell to show light levels (presumably shows them as they are server-side)
![2024-04-14_22 55 43](https://github.com/copycats-plus/copycats/assets/45552594/4c9163ee-5b46-4096-a5f1-08f2d26b2483)
After relog, Haunted Bell confirms that light has disappeared.
![2024-04-14_22 56 47](https://github.com/copycats-plus/copycats/assets/45552594/af507fef-6a4b-4095-b72b-fc70cd5f0837)
Happens without shaders too.
![2024-04-14_23 02 18](https://github.com/copycats-plus/copycats/assets/45552594/47f05ce4-1a07-4c0d-901c-55fb9fb82280)
Using latest version, Forge 1.20.1, v1.2.6
I am using many other mods, including Embeddium and Oculus for shaders.

**Comment by hlysine** [comment]
This is a bug in Create itself unfortunately. https://github.com/Creators-of-Create/Create/issues/4889
