### ISSUE TITLE
Disabling blocks in config does not affect stonecutter recipes

### ISSUE THREAD

**Issue by totrider** [copycats-plus/copycats#45]
After disabling blocks in the config, you can still make them through the stonecutter.

![image](https://github.com/copycats-plus/copycats/assets/1184655/41927a51-819e-47b4-991f-a9c1a641b526)

![image](https://github.com/copycats-plus/copycats/assets/1184655/ba0a2ee3-4346-4d9a-9bcb-9557d1ee69cc)

![image](https://github.com/copycats-plus/copycats/assets/1184655/cbc00bdc-5185-4515-9f09-fb4366218aea)

Both client and server has the same config for disabled blocks, and I can in fact make them still.

**Comment by redboi18** [comment]
I do not believe its possible to make recipies configurable if there able to be used or not

**Comment by Kehnte** [comment]
Same problem here. Server has disabled blocks, and I can craft all of them.

**Comment by totrider** [comment]
I fixed the issue temporarily by making a simple datapack for my particular use-case. 

[dragons copycat disabler.zip](https://github.com/copycats-plus/copycats/files/15063584/dragons.copycat.disabler.zip)

**Comment by totrider** [comment]
Just updated my modpack today, and this issue still persists.

**Comment by hlysine** [comment]
This has been fixed. Disabled items should be properly hidden and made uncraftable in the next update.
