### ISSUE TITLE
[Suggestion] Finer pick block control

### ISSUE THREAD

**Issue by AstralOrdana** [copycats-plus/copycats#48]
Currently, when you use the pick block control (middle mouse) on a copycat block, it will give you the block whos texture has been applied to it, this is consistent with base create but in most cases not the most helpful when building. I propose that normal pick block for these copycats should give you the empty copycat *unless* you ctrl + middle click in which case it gives you the block that was applied to it.

**Comment by Bennyboy1695** [comment]
We just extend the base create copycat block for ours. So changing its behavior while possible isn't really something we want to do as it will make it more confusing

**Comment by theTaeco** [comment]
Also iirc shift rclick gives the copycat block

**Comment by AstralOrdana** [comment]
> Also iirc shift rclick gives the copycat block

damn, youre right lmfao
i could have sworn i tried this before making the suggestion. carry on
