### ISSUE TITLE
Copycat trapdoors cant be climbed with ladders

### ISSUE THREAD

**Issue by LadyStrella** [copycats-plus/copycats#50]
on vanilla minecraft, you are able to climb trapdoors as long as there is a ladder right under, that feature is not present for copycat trapdoors.

**Comment by CaptainSqrBeard** [comment]
I have the same issue with `copycats-1.3.8+mc.1.20.1-fabric`. Very inconvenient as trapdoors used with ladders fairly often

**Comment by hlysine** [comment]
Fixed in code. Will be released in v2.0
