### ISSUE TITLE
[Bug] Copycats of light emitting blocks stop emitting light.

### ISSUE THREAD

**Issue by 40411** [copycats-plus/copycats#52]
When applying a light source block onto a copycat, for example a Block of Experience (from Create) onto a Copycat, the block will emit light as normal;
![image](https://github.com/copycats-plus/copycats/assets/80294264/56366cc5-2caa-460e-80d3-2334f2a38ecb)
But, as soon as those chunks are unloaded and reloaded, such as leaving and entering those chunks again, or leaving and rejoining a world, the light level is lost;
![image](https://github.com/copycats-plus/copycats/assets/80294264/1e9bdd0f-941d-47d5-b36e-f00d2f312c12)
The light level can return if another light emitting block is placed, or one gets close to it with the Dynamic Lights mod, but the light from the updated Copycat blocks will not update other Copycat blocks;
![image](https://github.com/copycats-plus/copycats/assets/80294264/cb43e370-72db-42a2-bd30-84a81f693e6a)

**Comment by Bennyboy1695** [comment]
This is a bug from Create itself as all our current copycats just extend the base copycat class in create.
You can see the issue on the Create github issue here - https://github.com/Creators-of-Create/Create/issues/4889
