### ISSUE TITLE
issue with VS Eureka + copycat

### ISSUE THREAD

**Issue by nul666lun** [copycats-plus/copycats#56]
when i build a ship... assemble it all is well.. align then disassemble.. Every copycat Stair piece is rotated ..and some copycat panels are shifted one tile away.. very odd issue.. im at a loss.... fabric 1.20.1

**Comment by AdamProGamingTR** [comment]
thats a eureka/vs2 issue and cant really be fixed

**Comment by hlysine** [comment]
There is a fix for block transforms in the upcoming release which might help with this issue, but it depends on how VS2 handles disassembly.
