### ISSUE TITLE
Breaking Particles are Missing Textures when Continuity is installed

### ISSUE THREAD

**Issue by MentoskaPraha** [copycats-plus/copycats#57]
# Description
When you install [Continuity](https://modrinth.com/mod/1IjD5062) along side [Create: Copycats+](https://modrinth.com/mod/UT2M39wf), the textures for the breaking particles of all copycat blocks will be missing. This issue occurs on Fabric and Quilt. I am unsure whether this is a [Continuity](https://modrinth.com/mod/1IjD5062) or [Create: Copycats+](https://modrinth.com/mod/UT2M39wf) issue, however the logs seem to point the blame at [Create: Copycats+](https://modrinth.com/mod/UT2M39wf). If I'm incorrect please let me know so I can report the issue to the correct party and it can get resolved.

## Observed Result
https://github.com/copycats-plus/copycats/assets/103432169/5a0760f9-f9d6-4b88-87e7-5b5699a632a8

## Expected Result
https://github.com/copycats-plus/copycats/assets/103432169/62342b97-85b9-4828-b6d7-99d017046082

# Game and Mod Versions
- Minecraft (`1.20.1`)
- Fabric Loader (`0.15.11`)
- Fabric API ([`0.92.2+1.20.1`](https://modrinth.com/mod/P7dR8mSH/version/P7uGFii0))
- Create Fabric ([`0.5.1-f-build.1417+mc1.20.1`](https://modrinth.com/mod/Xbc0uyRg/version/h2HgGyvA))
- Create: Copycats+ ([`1.20.1-1.2.6`](https://modrinth.com/mod/UT2M39wf/version/jjhScGWs))
- Continuity ([`3.0.0-beta.5+1.20.1`](https://modrinth.com/mod/1IjD5062/version/84Zs6tNo))

# Steps to Reproduce
1) Setup Fabric with the mod list above
1) Apply both resourcepacks provided by Continuity named: Glass Pain Culling Fix and Default Connected Textures, with Glass Pain Culling Fix being above Default Connected Textures.
1) Create and join a new world
1) Place down any Copycat block
1) Break the placed copycat block, the break particle textures should now be missing

# Logs
Logs of the session where the issue occurred can be found [here](https://mclo.gs/KrqAELw). No crash reports or other log files were created by the game.

**Comment by Bennyboy1695** [comment]
Does this also happen with the copycats from Create or just our mod?

**Comment by MentoskaPraha** [comment]
> Does this also happen with the copycats from Create or just our mod?  

Both. 

Also, I forgor to add that continuity resourcepacks Glass Pain Culling Fix and Default Connected Textures need to be applied.

**Comment by Bennyboy1695** [comment]
> > Does this also happen with the copycats from Create or just our mod?
> 
> Both.
> 
> Also, I forgor to add that continuity resourcepacks Glass Pain Culling Fix and Default Connected Textures need to be applied.

If this is the case that it happens with both then its actually an issue with Create as we just extend the base copycat class from Create currently to make ours

**Comment by MentoskaPraha** [comment]
Understood, I'll go report the issue to Create.
Have a great day.
