### ISSUE TITLE
Light glitch 

### ISSUE THREAD

**Issue by arhp777** [copycats-plus/copycats#60]
I use 1.20.1 mc and copycats 1.2.6
If put glowstone in copycats block and reenter the world the block doesn't glow.

**Comment by Bennyboy1695** [comment]
Duplicate of https://github.com/copycats-plus/copycats/issues/52. Also an issue in creates copycat class which we extend

**Comment by arhp777** [comment]
There is written, that I have to edit file inside create mod. Do you know how?

**Comment by hlysine** [comment]
You should leave this to the Create devs. That comment is just a workaround in the source code and editing source code is quite complex.
