### ISSUE TITLE
Copycat trapdoors ignore sneaking player's interaction

### ISSUE THREAD

**Issue by VladisCrafter** [copycats-plus/copycats#61]
...even if sneaking is NOT caused by holding `shift`.

Expected behavior: they should be interactable no matter what position the player is in. Unless holding `shift` or any other key binded to "crouch". __Like vanilla trapdoors are.__

https://github.com/copycats-plus/copycats/assets/122053125/b97cfd61-a7dd-47f4-bf2d-db66fc2195e6

**Comment by VladisCrafter** [comment]
P.S. I just realized that framed glass trapdoors from base Create do not have this issue and look almost the same. So I'll be using them in this case.

### Issue priority level: probably not high :]

**Comment by theTaeco** [comment]
isn't this caused by the toggle connected textures feature? its probably better this way so we can toggle connected textures without opening the trapdoor

**Comment by VladisCrafter** [comment]
@theTaeco "toggle connected textures" should be triggered by R-click **while sneaking**. While YOU are actually sneaking and NOT when something is squishing your body to the sneaking state. As I've said, **I wasn't pressing** `shift`, so even if "toggle connected textures" was actually triggered (there was no way I could even notice), then **it's still wrong behavior!**

**Comment by Bennyboy1695** [comment]
Actually the way things check if you pressing the sneak button is by checking if your pose is crouching. Which means that while you were under that trapdoor your pose was forced to be crouching and therefore were considered to be pressing the sneak button. 
I do have to say that the toggle connected textures isnt on the trapdoor though as it doesn't have connected textures

**Comment by VladisCrafter** [comment]
@Bennyboy1695 then why am I able to interact with vanilla and base Create trapdoors normally? 🤨

**Comment by hlysine** [comment]
There is a check for whether the player is holding shift. Using that check instead of `isCrouching` fixes the issue.
