### ISSUE TITLE
Unable to use tools

### ISSUE THREAD

**Issue by Vikthos** [copycats-plus/copycats#62]
Tools don't work in version 1.20.1-1.3.0 due to issue with tag.

**Comment by Bennyboy1695** [comment]
Not sure i fully understand the issue.
Which tools don't work?
And whats the issue with the tag?

**Comment by Vikthos** [comment]
I think its similar to this but idk https://www.reddit.com/r/Minecraft/comments/13knzks/tools_cant_seem_to_break_blocks_as_normal_with/ when mining a block with for example a wooden pickaxe it acts as if I were mining it with my hand

**Comment by Bennyboy1695** [comment]
What are you trying to mine? And with what tool?

**Comment by Vikthos** [comment]
stone with wooden pickaxe and logs with wooden axe

**Comment by Bennyboy1695** [comment]
have just confirmed this is an issue. Working on fixing it now

**Comment by Bennyboy1695** [comment]
Fixed in the latest version uploading to CurseForge and Modrinth now :)
