### ISSUE TITLE
[Suggestion] Copycat Doors

### ISSUE THREAD

**Issue by VectorGames1** [copycats-plus/copycats#67]
I was trying to make a cool concrete base but there is no door which would match the shade, the most similar block i could find is the warped door but it's way to dark for my build which is so  frustrating having an entire base of conrete and a wierd wooden door at the entrance so
i want you to implement a copycat door which can like the trapdoor can open and close and be powered by redstone

**Comment by vaaski** [comment]
duplicate of #13
