### ISSUE TITLE
[Bug] Player gets stuck on lower step of copycat stairs block

### ISSUE THREAD

**Issue by SageofTurtles** [copycats-plus/copycats#68]
**Describe the bug**
This is a very strange (and probably very specific) bug I've just encountered, where when walking off the edge of a copycat stairs block, my player will sometimes become immobilized when standing on the lower half of the stair step.  I am unable to walk, sprint, jump, or fly, and can only rotate my player and crouch while immobilized like this.  I was forced to use an enderpearl or /tp command to remove myself from that position.  It only seems to occur when the player is on the lower step, and I've only been able to reproduce this when walking off of a ledge (such as a rooftop), but not with 100% consistency.  I have no clue what is causing this, and have verified that I wasn't wearing any items that could be triggering an effect I was unaware of.  I've attached a video recording below, each time you see me freeze and rotate prior to using an enderpearl in the video shows when I was stuck and unable to move in any direction.  I'm happy to provide any further information on request, but like I said, can't find a pattern as to what's causing this other than I've only seen it with the copycat stairs so far.

**To Reproduce**
1. Install the modpack (not sure what a "minimal instance" would include for this bug, but all mods installed are in this text file):  
[Mods List.txt](https://github.com/user-attachments/files/15879841/Mods.List.txt)
2. Attempt to walk off various copycat stairs ledges, making sure to step on the lower step of the block.
3. Sometimes become immobilized, other times not.  I genuinely have no idea what the deciding factor here is.  (This may not even be a Copycats+ issue, I just couldn't think of anything else that might be related.  If not, I apologize!)

**Expected behavior**
Player should be able to move freely when walking across copycat blocks.

**Screenshots**
https://github.com/copycats-plus/copycats/assets/36843625/23c79212-d1c1-4fe4-b5d7-1bc22814edb8

**Desktop (please complete the following information):**
 - Minecraft Version:  1.20.1
 - Mod Loader:  Fabric 0.15.11
 - Mod Version:  1.3.2

**Comment by SageofTurtles** [comment]
Update:  One of my players just reported that he's also encountering this issue with copycat slabs, so this may not be limited to stairs after all.

**Comment by Bennyboy1695** [comment]
Whats even more confusing about this is that the stairs extend create's copycat class meaning methods like walking on, falling on block etc are already handled by create so the fact the same issue occurs on the slabs which are handled by our own system is very confusing.
What blocks are in the stairs? Im thinking maybe its an issue with the material causing some issue

**Comment by SageofTurtles** [comment]
It seems to only be happening with modded blocks so far, but we didn't encounter this issue prior to updating to 1.3.2, so maybe a new conflict? So far we've seen it happen with industrial iron from Create, umber bricks from Create Deco, and a few different stone-type brick blocks from Chipped.

**Comment by SageofTurtles** [comment]
Looking into this more, it seems to be happening only when walking over a copycat-type block with another copycat-type directly underneath it. I haven't been able to test this very extensively yet, but that is looking like the condition in the instances we've seen so far.

**Comment by Bennyboy1695** [comment]
Just run into this myself but only after i left the dev enviroment.
Per chance is the copycat underneath one of the multistates?

**Comment by SageofTurtles** [comment]
I honestly don't understand what multistates are or how to tell if the block is one, so I couldn't really tell you, sorry! They were the copycat slabs (vertical and horizontal both) and stairs underneath the block that was being stood on, if that helps.

**Comment by Bennyboy1695** [comment]
Multistates are the blocks that support multiple textures in the same block space. So slabs, bytes etc

**Comment by SageofTurtles** [comment]
Ah, thanks for clarifying. The stairs underneath the block actually seem to be fine after all, but slabs under the block are causing the issue, so that might be it.

**Comment by Bennyboy1695** [comment]
Yeah i have an idea whats casuing it then. If i'm right it should be very simple to fix and will have an update out shortly

**Comment by Bennyboy1695** [comment]
Will push an updated build to CurseForge and Modrinth shortly. Thanks for being so helpful finding the issue 😄

**Comment by Bennyboy1695** [comment]
Update is now on both sites

**Comment by SageofTurtles** [comment]
Happy I could help! My server and I appreciate the quick fix. We'll install the latest update later today. Thank you!
