### ISSUE TITLE
[Bug] Recently changed board/multiblock behavior broke connected texturing

### ISSUE THREAD

**Issue by Vectrobe** [copycats-plus/copycats#70]
**Describe the bug**
With at least the boards, which allow placing of multiple boards to seperate sides within a single block, the connected texturing behavior broke with the change that allowed individual sides to have seperate textures, with the South, East and Up surfaces within a block being broken, however North, West and Down still maintain normal connected texture behavior.

To further clarify; connected texture bug occurs to all faces of the boards within the affected faces of the block, so a board placed on the Up face within a block will have both the Up and Down faces broken, but with a board placed on the Down face of the block the Up and Down faces will behave as expected. The bug specifically occurs with the *position* of the given board and not its actual faces.

**To Reproduce**
place boards around different surfaces and you can see which of the 6 sides are affected or not

**Expected behavior**
connected textures

**Screenshots**
![image](https://github.com/copycats-plus/copycats/assets/3912867/ceeefb9f-d796-40b9-8391-edfbded5b8bd)

**Desktop (please complete the following information):**
 - Minecraft Version: 1.20.1
 - Mod Loader: neoforge 47.1.105
 - Mod Version: 1.3.4

**Additional context**
doesnt seem to matter whether the boards pre-existed before the update or they are placed as new, issue was immediately discovered after updating the mod since I use the boards extensively with both repeating and non repeating texture blocks, but only from vanilla and create

**Comment by Bennyboy1695** [comment]
The issue of the boards only connecting in some directions is known but is a very complicated solve due to the way we handle the connected textures on the multistate blocks. Its being worked on but may take a while before its fixed due to the complexity

**Comment by hlysine** [comment]
Fixed in code and will be released in the next update. A tester version is available on our discord server
