### ISSUE TITLE
[Bug] Copycat cat entity texture reverted and I'm trying to figure out the variant tag to change it back

### ISSUE THREAD

**Issue by CleverBalloon** [copycats-plus/copycats#74]
This is technically a bug but it has an incredibly simple fix to my knowledge. So I love the copycat cats and I had one but it randomly changed back into a normal cat. I'm doing a data command to change it back using

/data merge entity @e[type=cat,limit=1,sort=nearest] {variant:red}

but for the life of me I cant work out what the variant of the cat is. I've tried copycat, copy, COPY_CAT, etc. I've looked through the source code and found the Catmixin.java file which referenced the cat variant but please I need help finding the actual keyword to use. Any help would be amazing, sorry as I know I didn't include a lot of the preferred data as this isn't a game breaking bug.

**Comment by theTaeco** [comment]
pretty sure these were removed in the multiloader update, but they're working on bringing them back

**Comment by CleverBalloon** [comment]
Oh that makes sense. Thanks so much for your help <3

**Comment by hlysine** [comment]
The copy cat is already back since 1.3.2. You can turn a normal cat into a copy cat by right-clicking it with a copycat block. For commands, the variant ID is `copycats:copy_cat`, so you need to write 
```
/data merge entity @e[type=cat,limit=1,sort=nearest] {variant:"copycats:copy_cat"}
```
For 1.18, the variant ID is 11.

**Comment by theTaeco** [comment]
mb, haven't been keeping up with updates as I've been on 1.2.8 for a modpack for a while now
