### ISSUE TITLE
1.20.1 latest forge server won't start

### ISSUE THREAD

**Issue by DogeKingChris** [copycats-plus/copycats#77]
**Describe the bug**
server crashes with the new copycats. removing new and suing old works perfect.

**To Reproduce**
1.update copycat on server
2.start server
3.watch it crash
4.cry

**Expected behavior**
no crash

**Screenshots**
i dont think screenshots are necessary

**Desktop (please complete the following information):**
1.20.1
forge
latest (1.3.6)

**Comment by Bennyboy1695** [comment]
Please post the crash report

**Comment by LeaderbotX400** [comment]
@Bennyboy1695 

Not OP, but same issue

https://gist.github.com/LeaderbotX400/111c8824310f2642559515f5576dbd1a

**Comment by Dumpling00** [comment]
Same issue here but on Fabric 1.20.1
Installing the new versions (From 1.3.5 onwards) suddenly causes the server to not start.
Suddenly seems to conflict with all things Create related.

https://gist.github.com/Dumpling00/f4af4b8452044cc0e1434e3b970a7a3f

**Comment by Mikeatron-User** [comment]
Same Issue
Crash log: https://mclo.gs/92tL3l9

**Comment by hlysine** [comment]
This has been fixed in release 1.3.8.
