### ISSUE TITLE
[Bug] crash when running server with other mods [1.20.1 forge 47.3.0]

### ISSUE THREAD

**Issue by wesley-jpeg** [copycats-plus/copycats#81]
here is are the logs, i dunno how to read them, i honestly just brute forced which mod was causing a crash lol.
log: https://pastebin.com/crTX8nt7
crash report: https://pastebin.com/dfyFX52b

**Describe the bug**
when running this mod on a SERVER with many others, it causes a crash. i am not that good at troubleshooting which mod it conflicts with, but it crashes lol.

**Expected behavior**
server is supposed to run, but conflicts with something. it only happens when trying to boot up a server, it works perfectly fine with other mods on singleplayer. weird.

**To Reproduce**
1. open server
2. crashes
3. See error

**Desktop (please complete the following information):**
 - Minecraft Version: 1.20.1
 - Mod Loader: Forge
 - Mod Version: 47.3.0

**Comment by Bennyboy1695** [comment]
This bug was already fixed. Please update your version of copycats+ to the latest (1.3.8)

**Comment by hlysine** [comment]
This issue has already been fixed. Please update to the newest version on both clients and the server.
