### ISSUE TITLE
[Bug] Create Copycats and Antique Atlas 4 partial incompatibility 

### ISSUE THREAD

**Issue by Penty2** [copycats-plus/copycats#90]
Game crashes upon first entering other dimension when both mods are installed.

Create Copycats version 1.3.8
Antique Atlas 4 version 2.9.11
 - Create new world.
 - Create Nether portal and enter it.

Minecraft Version: 1.20.1
Mod Loader: NeoForge, Fabric

(it may not mean anything but I noce saw mention of Surveyor Map Framework in logs, which is base for Antique Atlas 4)

**Comment by Bennyboy1695** [comment]
Can we get the crash report please.

**Comment by Penty2** [comment]
https://mclo.gs/A8N95Dt

**Comment by Penty2** [comment]
here is NeoForge crash report https://mclo.gs/vxVV2J1

**Comment by Bennyboy1695** [comment]
Its the same crash on both loaders it seems. But the issue isn't caused by copycats so you will be better off reporting this to the mod devs of the Surveyor mod as its an issue within their mod.
