### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Whoosfer** [copycats-plus/copycats#95]
**Describe the bug**
So Copycats+ created a tessellated block upon moving something with a copycatted block with Axiom.

**Expected behavior**
Moving the selected Axiom object back by one.

**Desktop:**
 - Minecraft Version: 1.20.1
 - Mod Loader: Fabric
 - Mod Version: copycats-1.3.8+mc.1.20.1-fabric.jar

**Additional context**
I really don't wanna lose my world, and i forgot to back it up.

**Log**
[latest.log](https://github.com/user-attachments/files/16239966/latest.log)

**Comment by Bennyboy1695** [comment]
That log doesnt seem to contain an error with the issue. Did your game crash?

**Comment by Whoosfer** [comment]
> That log doesnt seem to contain an error with the issue. Did your game crash?

Yes, Lemme send the crash report instead.
[crash-2024-07-15_15.59.35-client.txt](https://github.com/user-attachments/files/16240032/crash-2024-07-15_15.59.35-client.txt)

**Comment by Bennyboy1695** [comment]
It seems that axiom hasn't set the blockstate/block data correctly, so has broken the block from knowing how to render each piece correctly.

**Comment by Whoosfer** [comment]
> It seems that axiom hasn't set the blockstate/block data correctly, so has broken the block from knowing how to render each piece correctly.

I removed Axiom and it still didn't work.

**Comment by Bennyboy1695** [comment]
yeah removing axiom wont solve the issue as its placed the block with incorrect information. You need to remove that block to fix your world
