### ISSUE TITLE
Hungarian Translation

### ISSUE THREAD

**Issue by Fischer1000** [copycats-plus/copycats#99]
A few days ago I translated all of the texts on Crowdin to Hungarian but due to Crowdin's nature, it replaced some of the translations with a worse one. (namely, 'imitátor' to 'kaméleon'.)
I tried my best to replace it on Crowdin, but I had no success.
Could You please do something in the favour of this?

**Comment by hlysine** [comment]
I see on GitHub that most of the translations have been corrected, but I've also made you a proofreader for Hungarian on Crowdin so you can overwrite the translations
